#include<stdio.h>
#include<conio.h>
void main()
{
 int num=0, rem=0;
 clrscr();
 printf("Enter Four digit number");
 scanf("%d",num);
 rem=num%100;
 printf("\n Extracted number is\t",rem);
 getch();
}       #include<stdio.h>
#include<conio.h>
void main()
{
 int num=0, rem=0;
 clrscr();
 printf("Enter Four digit number");
 scanf("%d",num);
 rem=num%100;
 printf("\n Extracted number is\t",rem);
 getch();
}